[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ipeaindices"
version = "0.1.0"
description = "Ãndices do IPEA de forma simples"
readme = "README.md"
authors = [
  { name = "nukhes", email = "nukhes@protonmail.com" }
]
requires-python = ">=3.7"
dependencies = ["ipeadatapy"]

classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Topic :: Scientific/Engineering :: Information Analysis"
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["ipeaindices"]
exclude = ["tests*"]
