[tool.poetry]
name = "cyanprintsdk"
version = "2.0.1"
description = "CyanPrint SDK for building templates, extensions, plugins or processors"
authors = ["Ernest Ng <ernest@atomi.cloud>"]
license = "MIT"
homepage = "https://docs.cyanprint.dev"
repository = "https://github.com/AtomiCloud/sulfone.helium"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.6"
pydantic = "^2.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
