[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "certbot-dns-dnsprivacy"
version = "0.3.0"
description = "Certbot DNS Plugin for the UK DNS Privacy Project"
authors = [{ name = "Paul Trippett", email = "support@dnsprivacy.org.uk" }]
license = { file = "LICENSE" }
readme = "README.md"
keywords = ["certbot", "dns", "letsencrypt"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'certbot>=2.0.0', 
    'requests'
]

[project.urls]
Homepage = "https://dnsprivacy.org.uk/"
Issues = "https://github.com/UK-DNS-Privacy-Project/certbot-dns-dnsprivacy/issues"