[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cfcommander"
version = "0.1.15"
description = "A simple Cloudflare DNS CLI tool"
authors = [{ name = "Jakub Jim Zacek", email = "jakub@zacekj.cz" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "tabulate",
]

[project.scripts]
cf = "cfcommander.__main__:main"

[tool.hatch.build.targets.sdist]
include = ["cfcommander/**"]

[tool.hatch.build.targets.wheel]
packages = ["cfcommander"]
