[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "castor-pollux"
version = "0.0.11"
authors = [
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"},
]
description = "A library for 'gemini' languagemodels without unnecessary dependencies."
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
dependencies = [
    "requests >= 2.32.3",
    "PyYAML >= 6.0.0",
]
[project.optional-dependencies]
gemini_google = ["google-genai >= 1.11.0"]
[project.urls]
"Homepage" = "https://github.com/alxfed/castor-pollux"
"Bug Tracker" = "https://github.com/alxfed/castor-pollux/issues"
