[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "econutils"
version = "0.1.3"
description = "utility function for econsystem"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "Tetragram", email = "tetragramdev@gmail.com"}
]

[tool.setuptools]
packages = ["econutils"]
package-dir = {"" = "src"}
