# @package loss.cls

# LICENSE HEADER MANAGED BY add-license-header
#
# SPDX-FileCopyrightText: Copyright 2024 German Cancer Research Center (DKFZ) and contributors.
# SPDX-License-Identifier: MIT
#

###
# default: :class:`~torch.nn.CrossEntropyLoss`
#  - pytorch cross entropy loss
_target_: torch.nn.CrossEntropyLoss
