[project]
name = "pykeyboard2"
version = "0.2.0a3"
authors = [
    { name = "Vivek Kumar" }
]
description = "Best Keyboard and Pagination for the Pyrogram Library."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License"
]
license = { text = "MIT" }

dependencies = []

[project.urls]
Source = "https://github.com/Vivekkumar-in/pykeyboard"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
