[project]
name = "lkr-cli"
version = "0.0.2"
description = "lkr: a command line interface for looker"
readme = "README.md"
license = "MIT"
authors = [
    { name = "bwebs"}
]
requires-python = ">=3.12"
dependencies = [
    "looker-sdk>=25.4.0",
    "pydantic>=2.11.4",
    "typer>=0.15.2",
    "requests>=2.31.0",
    "cryptography>=42.0.0",
    "pick>=2.4.0",
    "pydash>=8.0.5",
    "structlog>=25.3.0",
]

[project.scripts]
lkr = "lkr.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.11.7",
]

[tool.hatch.build.targets.wheel]
packages = ["lkr"]
