[build-system]
requires = [
    "setuptools>=43.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "obz"
description = "OBZ"
version = "121"
authors = [
    {name = "Bart Thate",email = "bthate@dds.nl"},
]
readme = "README.rst"
license = {text="Public Domain"}
dependencies = [
    'obr',
    'obx'
]
classifiers = [ 
    'Development Status :: 1 - Planning',
    'License :: Public Domain',
    'Programming Language :: Python',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Libraries :: Python Modules'
]


[project.urls]
"home" = "https://pypi.org/project/obx"
"bugs" = "https://github.com/bthate/obx/issues"
"source" = "https://github.com/bthate/obx"


[tool.setuptools]
script-files = [
    "bin/obz",
]
packages = [
    "obz",
    "obz.modules"
]
