[project]
name = "detoxai"
version = "0.3.7"
description = "todo"
readme = "README_pypi.md"
requires-python = ">=3.11"
authors = [
    { name = "Łukasz Sztukiewicz", email = "contact@lukaszsztukiewicz.com" },
    { name = "Ignacy Stępka", email = "ignacy.stepka@student.put.poznan.pl" },
    { name = "Michał Wiliński", email = "michal.wilinski@student.put.poznan.pl" }
]
dependencies = [
    "gdown>=5.2.0",
    "lightning>=2.4.0",
    "torchvision>=0.20.1",
    "pillow>=11.0.0",
    "tqdm>=4.67.1",
    "concept-erasure>=0.2.4",
    "scikit-learn>=1.6.0",
    "scikit-optimize>=0.10.2",
    "pandas>=2.2.3",
    "zennit>=0.5.1",
    "matplotlib>=3.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pre-commit>=4.2.0",
]
docs = [
    "nbsphinx>=0.9.6",
    "pandoc>=2.4",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
