[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "grammateus"
version = "0.1.1"
authors = [
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"},
]
description = "A role responsible for documenting legal proceedings in Greece"
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
keywords = ["grammateus", "recording", "ai"]
dependencies = [
    "requests >= 2.32.3",
    "jsonlines >= 4.0.0",
    "PyYAML >= 6.0.2"
]
[project.optional-dependencies]
arrow = ["pyarrow >= 20.0.0"]
[project.urls]
"Homepage" = "https://github.com/multilogue/grammateus"
"Bug Tracker" = "https://github.com/multilogue/grammateus/issues"