[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "askmydb"
version = "0.1.3"
description = "A Python package for querying databases using natural language."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [{ name = "Shanthosh" }]
dependencies = [
    "sqlalchemy"
]

[project.optional-dependencies]
dev = ["black", "pytest"]
openai = ["openai"]
ollama = ["ollama"]
all = ["sqlalchemy", "black", "pytest", "openai", "ollama"]

[tool.setuptools.packages.find]
where = ["askmydb"]

[tool.bump2version]
current_version = "0.1.0"
commit = true
tag = true

[tool.bump2version.file."pyproject.toml"]
[tool.bump2version.file."src/ask_mydb/__init__.py"]
