########################################################################
###############################  BUILD  ################################
########################################################################
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

########################################################################
##############################  PROJECT  ###############################
########################################################################
[project]
name = "fastcc"
version = "4.0.8"
description = """\
    Lightweight, efficient and developer-friendly framework for mqtt \
    communication.
"""
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "J. Baudisch", email = "justin.baudisch@hsbi.de" }]
maintainers = [{ name = "J. Baudisch", email = "justin.baudisch@hsbi.de" }]
keywords = ["mqtt", "protobuf", "aiomqtt", "asyncio", "iot"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Topic :: Communications",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",
]
dependencies = [
    "aiomqtt == 2.3.0",     # Asynchronous MQTT Client (https://github.com/empicano/aiomqtt)
    "protobuf == 6.30.1",   # Data Serialization (https://github.com/protocolbuffers/protobuf)
]

[project.optional-dependencies]
dev = [
    "ruff == 0.11.0",       # Linter & Formatter (https://pypi.org/project/ruff)
    "mypy == 1.15.0",       # Static Type Checker (https://pypi.org/project/mypy)
    "Sphinx == 8.2.3",      # Documentation Generator (https://pypi.org/project/Sphinx)
    "furo == 2024.8.6",     # Documentation Theme (https://pypi.org/project/furo)
    "types-protobuf == 5.29.1.20250315",  # Protobuf Type Hints (https://pypi.org/project/types-protobuf)
]

[project.urls]
Repository = "https://github.com/ReMi-HSBI/fastcc"

########################################################################
###############################  TOOLS  ################################
########################################################################
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"fastcc" = ["py.typed"]
