[build-system]
requires = [
  "setuptools>=61",     # or bump to 68+ if you want PEP621 support, but not required here
  "wheel",
  "pybind11>=2.6.0",    # weâ€™ll use pybind11.setup_helpers in setup.py
  "ninja",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
environment = { PIP_NO_COMPILE = "1", CMAKE_GENERATOR = "Ninja" }
test-command = "python -c \"import VegasAfterglow; print('OK')\""