[project]
name = "snowflake-opendic"
version = "0.1.22"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "akongstad", email = "kongstad@outlook.com" },
    { name = "carlbrr", email = "carl99@live.dk"},
]

requires-python = ">=3.9"
dependencies = [
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "snowflake-connector-python[pandas]>=3.13.2",
    "toml>=0.10.2",
]

[project.scripts]
snowflake-opendic = "snowflake_opendic:main"

[build-system]
requires = ["uv_build>=0.6.5,<0.7"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
]

[project.urls]
Homepage = "https://github.com/msc-open-metadata/snowflake-opendic"
