[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "bvhTools"
version = "0.1.4"
authors = [
  { name="Eneko Assets", email="enekoassets@gmail.com" },
]
dependencies = [
    "scipy==1.14.0",
    "numpy==1.26.4",
    "matplotlib==3.9.0"
]
description = "Easy to use package to work with BVH (BioVision Hierarchy) files."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Enekoassets/bvhTools"
Issues = "https://github.com/Enekoassets/bvhTools/issues"
Documentation = "https://enekoassets.github.io/bvhTools/"