[project]
name = "mcp-server-gad"
version = "0.0.4"
description = "A secure MCP server that provides a read-only PostgreSQL query tool for gad."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "mcp>=1.7.1","sqlalchemy", "psycopg2-binary"]

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-server-gad = "mcp_server_gad:main"
