[tool.poetry]
name = "statql"
version = "0.1.4"
description = "Approximate, streaming SQL engine"
authors = ["liel <liellahat@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.11.3"
pandas = "^2.2.3"
platformdirs = "^4.3.7"
streamlit = "^1.44.1"
sqlglot = "^26.13.0"
psycopg = { extras = ["binary"], version = "^3.2.6" }
streamlit-code-editor = "^0.1.22"
duckdb = "^1.2.2"
redis = "^5.2.1"

[tool.poetry.scripts]
statql = "statql.__main__:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
tabulate = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
