[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "formflow"
version = "1.0.27"
authors = [
    { name="Mizuki Hikaru", email="mizuki@hikaru.org" },
]
description = "FormFlow allows easy 'Contact Us' form integration."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi[standard]",
    "authbase",
]

[project.urls]
Homepage = "https://github.com/mizuki-hikaru/formflow"
Issues = "https://github.com/mizuki-hikaru/formflow/issues"

[project.scripts]
formflow = "formflow:main"
