[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "strictprotocol"
version = "0.1.2"
description = "A stricter Protocol enforcement for Python"
authors = [{name = "Michael Afmokt", email = "michael@esacca.com"}]
license = "MIT"
license-files = ["LICENSE"]
keywords = ["protocol", "typing", "type-checking"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/afmkt/strictprotocol"
Repository = "https://github.com/afmkt/strictprotocol"
Issues = "https://github.com/afmkt/strictprotocol/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]