[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "uniconpy"
version = "1.0.0"
description = "Pacote para a conversão de unidades de massa, temperatura e volume"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}

authors = [
  {name = "matcomp", email = "projeto@matcomp.com.br"}
]


keywords = ["conversão", "temperatura", "massa"]

[project.urls]
Homepage = "https://github.com/seu_pacote"
Documentation = "https://github.com/seu_pacote/docs"


