[project]
name = "cashier-server"
version = "0.1.0"
description = "Cashier synchronization server in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.2",
]
