[project]
name = "orgm"
version = "0.121"
description = "ORGM CLI for managing projects and tasks"
readme = "README.md"
authors = [{name = "Osmar Garcia"}]
license = "Apache-2.0"
requires-python = ">=3.8"
classifiers = [
]
dependencies = [
    "kivy>=2.3.1",
    "nicegui>=2.15.0",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.0.1",
    "questionary>=2.1.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "setuptools>=75.3.2",
    "sqlmodel>=0.0.24",
    "textual>=0.73.0",
    "typer>=0.15.2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/osmargm1202/cli"

[project.scripts]
orgm = "orgm.orgm:main"

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
orgm = ["*"]

[tool.setuptools.package-dir]
"" = "."
