[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "model_monitoring"
version = "2.0.5"
authors = [
  { name="DAT Team Credem"},
]
description = "Model Monitoring"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies=[
    "typed-ast==1.5.4",
    "numpy==1.22.4",
    "pandas==1.5.3",
    "scikit-learn==1.2.1",
    "lightgbm==3.3.2",
    "scipy==1.10.1",
    "PyYAML==6.0",
    "shap==0.41.0",
    "ipython",
    "numba==0.60.0"
]
[project.urls]
"Homepage" = "https://dev.azure.com/credem-data/DAT/_git/model_monitoring"