[project]
name = "lazylee-mcp-test"
version = "0.4.0"
description = "mcp server test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.7.1",
]

[project.scripts]
lazylee-mcp-test = "lazylee_mcp_test.server:main"