[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "gway"
version = "0.0.53"
description = "Software Project Infrastructure by https://www.gelectriic.com"
requires-python = ">=3.7"
license = "MIT"
classifiers = [ "Programming Language :: Python :: 3", "Operating System :: OS Independent",]
dependencies = [ "toml", "setuptools", "twine", "build", "colorama",]
[[project.authors]]
name = "Rafael J. Guill√©n-Osorio"
email = "tecnologia@gelectriic.com"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.scripts]
gway = "gway:cli_main"

[project.urls]
repository = "https://github.com/arthexis/gway.git"

[tool.setuptools]
packages = [ "gway",]
