[project]
name = "meowmeowutils"
version = "0.1.0"
description = ""
authors = [
    {name = "Yoshika Govender", email = "yoshi.govender@gmail.com"}
]
keywords = ["file tools"]

readme = "README.md"
requires-python = ">=3.10"
dependencies = []

classifiers = [
    "Development Status :: 2 - Pre-Alpha"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/JetpackYoshi/meowmeow"