[package]
name = "devlacruz_hashlib"
version = "0.1.0"
edition = "2021"
description = "Extensi√≥n de hashing acelerado con Rust y PyO3"
license = "MIT"
repository = "https://github.com/DevLaCruz/devlacruz_hashlib"

[lib]
name = "devlacruz_hashlib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
sha2 = "0.10"
hex = "0.4"
