[project]
name = "xsection"
version = "0.0.3"
authors = [
  {name="Claudio M. Perez", email="50180406+claudioperez@users.noreply.github.com"}
]

readme = "README.md"

keywords = [
    "seismic",
    "earthquake",
] 

[options]
#packages = find
install_requires = [
  "numpy",
  "quakeio",
  "pygmsh",
  "meshio",
  "shps>=0.0.20",
  "veux",
  "cytriangle",
  "matplotlib",
  "plotly",
  "opensees",
  "quakeio"
]

[project.urls]
repository = "http://github.com/STAIRlab/xsection"
documentation = "https://brace2.github.io/xsection"

[project.scripts]
xsection = "xsection.__main__:main"

[build-system]
requires = [
    "setuptools >= 52.0.2",
]

build-backend = "setuptools.build_meta"

