[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "webscrapper-client-api"
version = "0.1.1"
description = "Async client for the webscrapper API"
readme = "README.md"
authors = [
    {name = "pi11", email = "webii@pm.me"},
]
license = {text = "WTFPL"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["webscrapper", "api", "client", "async", "proxy", "scraping"]
dependencies = [
    "aiohttp>=3.7.0",
]
requires-python = ">=3.7"
 
[project.urls]
"Homepage" = "https://github.com/yourusername/webscrapper-client-api"

[tool.setuptools]
packages = ["webscrapper_client_api"]

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
line_length = 88

