[project]
name = "mcp-wxdemo1-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "WangXiao", email = "wb-wx869082@alibaba-inc.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.7.1",
]

[project.scripts]
mcp-wxdemo1-server = "mcp_wxdemo1_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
