[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pstatstools"
dynamic = ["version"]
description = "Statistical tools package"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.19.0",
    "scipy>=1.7.0",
    "matplotlib>=3.4.0",
    "statsmodels>=0.13.0",
    "pandas>=1.3.0",
    "jinja2>=3.0.0"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pstatstools"]