# storage服务配置
# 基本数据存储路径
data_dir: /Users/hanswang/Desktop/long_road/DataWhale/data
# 运行信息存储路径
runtime_dir: /Users/hanswang/Desktop/long_road/DataWhale/runtime
# 日志存储路径 (相对于runtime_dir)
logs_dir: logs
# 元信息存储路径 (相对于runtime_dir)
metainfo_dir: metainfo
# 默认数据存储格式
format: csv
# 默认文件编码
encoding: utf-8 