[project]
name = "pentest_tls"
version = "0.1.11"
description = "A collection of Python pentest tools"
readme = "README.md"
authors = [{ name = "Owen Liu", email = "abcd0112014@gmail.com" }]
license = { text = "MIT" }
dependencies = [
    "pyfiglet>=1.0",
    "argparse",
    "scapy"
]

[project.scripts]
pentest_tls = "pentest_tls.cli.pentest_tls_cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { where = ["src"], namespaces = false } }