# @package augmentations

# LICENSE HEADER MANAGED BY add-license-header
#
# SPDX-FileCopyrightText: Copyright 2024 German Cancer Research Center (DKFZ) and contributors.
# SPDX-License-Identifier: MIT
#

normalization: imagenet  # image_net mean and std values are used
cpu:
  backend: albumentations
  pipeline:
    - name: RandomCrop
      height: 224
      width: 224
    - name: HorizontalFlip
      p: 0.5
    - name: RandAugment
      number: 3
      magnitude: 4
      mode: all
      p: 0.5
      cut_out: True
gpu: {}
