[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "computer-use-ootb-internal"
version = "0.0.177"
description = "Computer Use OOTB"
authors = [{ name = "Siyuan Hu", email = "siyuan.hu.sg@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "opencv-python",
    "ruff==0.6.7",
    "pre-commit==3.8.0",
    "pytest==8.3.3",
    "pytest-asyncio==0.23.6",
    "pyautogui==0.9.54",
    "streamlit>=1.38.0",
    "anthropic[bedrock,vertex]>=0.37.1",
    "jsonschema==4.22.0",
    "boto3>=1.28.57",
    "google-auth<3,>=2",
    "gradio>=5.6.0",
    "screeninfo",
    "uiautomation",
    "pywinauto",
    "textdistance",
    "matplotlib",
    "litellm",
    "PySide6",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.6.7",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.23.6",
]

[tool.hatch.build.targets.wheel]
packages = ["src/computer_use_ootb_internal"]
include = ["src/computer_use_ootb_internal/**/*"]  # This ensures all subpackages are included

[project.scripts]
computer-use-ootb-internal = "computer_use_ootb_internal.app_teachmode:main"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.hatch.metadata]
allow-direct-references = true