[tool.poetry]
name = "compile-minifier"
version = "0.2.1"
description = "Python compiler and minifier"
authors = ["Amoki <hugo@bimdata.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.urls]
homepage = "https://github.com/bimdata/compile-minifier"
repository = "https://github.com/bimdata/compile-minifier"

[tool.poetry.scripts]
compile-minifier = "compile_minifier.main:entrypoint"
compile-minify = "compile_minifier.main:entrypoint"


[tool.poetry.dependencies]
python = ">=3.5,<3.14"
python-minifier = "^2.11.3"
fire = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
