[project]
name = "bowentest1"
version = "0.1.11"
description = "测试mcp项目"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.6.0",
]


[project.scripts]
bowentest1 = "bowentest1:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
