[project]
name = "hsxworkflow"
version = "0.1.1"
description = "工作流软件"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiomysql==0.2.0",
    "async-timeout==5.0.1",
    "blinker==1.8.2",
    "certifi==2025.1.31",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "colorama==0.4.6",
    "cssselect==1.2.0",
    "datarecorder==3.6.2",
    "dill==0.4.0",
    "downloadkit==2.0.7",
    "drissionpage==4.1.0.18",
    "et-xmlfile==2.0.0",
    "filelock==3.16.1",
    "flask==3.0.3",
    "flask-cors==5.0.0",
    "flask-socketio>=5.5.1",
    "idna==3.10",
    "importlib-metadata==8.5.0",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "lxml==5.3.2",
    "markupsafe==2.1.5",
    "openpyxl==3.1.5",
    "pip==23.0.1",
    "psutil==7.0.0",
    "pymysql==1.1.1",
    "redis==5.2.1",
    "requests==2.32.3",
    "requests-file==2.1.0",
    "setuptools==56.0.0",
    "tldextract==5.1.2",
    "urllib3==2.2.3",
    "websocket-client==1.8.0",
    "werkzeug==3.0.6",
    "zipp==3.20.2",
]

[project.scripts]
hsxDev = "hsxworkflow:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["hsxworkflow"]

