[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "farmsks"
version = "0.1.2"
authors = [
    { name = "Samyar Sameni", email = "samyar4@gmail.com" }
]
description = "Useful defs"
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.build.targets.sdist]
exclude = ["NTUSER.DAT", "ntuser.dat.LOG1"]

[tool.hatch.build.targets.wheel]
packages = ["src/farmsks"]

license = { text = "LICENSE.txt" }