[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "taylor-sb-hello-world"
version = "0.2.0"
description = "A simple hello world example"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
hello = "hello_world.main:main" 
