[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "safe-flask"
version = "2.0.0"
description = "A plug-and-play firewall library for Flask applications."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "CodeGuardianSOF", email = "securex39@gmail.com" }
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: Flask",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "Flask>=1.1.2"
]

[project.urls]
Homepage = "https://github.com/CodeGuardianSOF/FlaskGuard"

[tool.setuptools.packages.find]
where = ["."]
