[tool.poetry]
name = "keble-db"
version = "0.1.20"
description = "Keble db"
authors = ["zhenhao-ma <bob0103779@gmail.com>"]
readme = "README.md"
packages = [{include = "keble_db"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.3.0"
qdrant-client = "^1.7.0"
redis = "^5.0.0"
sqlmodel = "^0"
pymongo = "^4.8.0"
keble_helpers = "^0"
motor = "^3"
deprecated = "^1"

[tool.poetry.group.test.dependencies]
pytest-asyncio = "^0.23.6"
pydantic-settings = "^2.2.1"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
