[package]
name = "oprc-py"
version = "0.1.19"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oprc_py"
crate-type = ["cdylib", "rlib"]

[dependencies]
envconfig = "0.11.0"
pyo3 = {version = "0.24", features = ["extension-module", "experimental-async"]}
pyo3-async-runtimes = { version = "0.24", features = ["attributes", "tokio-runtime"] }
pyo3-stub-gen = {version = "0.8"}
tokio = { version = "1", features = ["rt-multi-thread", "signal"] }
tonic = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zenoh = {version = "1.3"}
zenoh-config = {version = "1.3"}
# pyo3-python-tracing-subscriber ={ version = "0.1"}

oprc-offload = {git = "https://github.com/pawissanutt/oaas-rs", branch = "dev"}
oprc-zenoh = {git = "https://github.com/pawissanutt/oaas-rs", branch = "dev"}
oprc-pb = {git = "https://github.com/pawissanutt/oaas-rs", branch = "dev", features=["util"]}


[[bin]]
name = "stub_gen"
