[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bus-mgmt-dolt-mcp-server"
version = "0.1.21"
description = "Bus Management Dolt MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
                "fastmcp", 
                "requests",
                "argparse"
               ]

[project.scripts]
bus-mgmt-dolt-mcp-server = "bus_mgmt_dolt_mcp_server.bus_mgmt_dolt_mcp_server:main"

[tool.setuptools]
packages = ["bus_mgmt_dolt_mcp_server"]
