[project]
name = "mm_geo_coder"
version = "0.2.1"
description = "A Goe_coder to locate the coordinates of addresses from Myanmar"
authors = [{ name="myothida", email="mmdt@istarvz.com" },]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = ["regex", "rapidfuzz", "mm_address_parser"]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/myothida/mm_geo_coder"
Issues = "https://github.com/myothida/mm_geo_coder/issues"

[project.optional-dependencies]
dev = ["pytest", "black", "isort", "mypy"]

[tool.setuptools]
include-package-data = true
packages = ["mm_geo_coder"]


