[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zymoKrisIndex"
version = "0.0.3"
authors = [
  { name="Michael Weinstein", email="mweinstein@zymoresearch.com" },
]
description = "A package for calculating kmer complexity of sequences using Burrows-Wheeler compressibility."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic >= 2.0",
    "mpire >= 2.0",
]

[project.urls]
"Homepage" = "https://github.com/Zymo-Research/krisIndex"
"Bug Tracker" = "https://github.com/Zymo-Research/krisIndex/issues"