[build-system]
requires = ["requests", "pytz", "logzero", "sqlalchemy", "psycopg2-binary"]
build-backend = "setuptools.build_meta"

[project]
name = "dkrlog"
version = "2.1"
authors = [
  { name="Leticia Figueiredo", email="leticia.figueiredo@dkr.tec.br" },
]
description = "This library standardizes logs and exceptions, ensuring consistent error handling and tracking."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "pytz",
    "logzero",
    "sqlalchemy",
    "psycopg2-binary"
]
