[project]
name = "historify"
version = "0.3.0"
description = "A tool for revision-safe logging of file changes"
authors = [
    {name = "Kevin Bortis", email = "kevin@bortis.ch"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "configparser>=7.1.0",
    "blake3>=0.3.4",
    "pexpect>=4.9.0",
    "pycdlib>=1.14.0"
]
keywords = ["versioning", "changelog", "integrity", "cryptography"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Archiving",
    "Topic :: System :: Logging",
]

[project.scripts]
historify = "historify.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "historify", from = "src"}]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3.3"
black = ">=24.10.0"
flake8 = ">=7.1.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v"
testpaths = ["tests"]