[project]
name = "simple-state-tracker"

[tool.poetry]
name = "simple-state-tracker"
version = "0.1.5"
description = "A minimal, type-safe, file-backed state tracker using Pydantic models."
authors = ["Max Chis <maxachis@gmail.com>"]
license = "LICENSE"
readme = "README.md"
packages = [{ include = "simple_state_tracker" }]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.11"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/maxachis/simple-state-tracker"
Repository = "https://github.com/maxachis/simple-state-tracker"
Issues = "https://github.com/maxachis/simple-state-tracker/issues"